#!/bin/bash

if [ $# -lt 1 ] || [ $# -gt 3 ]; then 
	echo -e "ERROR: Please provide at least a commit message."
	exit 1;
fi

commit_message="$1"

echo " "
echo "======================================== AutoGit ========================================"
echo " "

echo -e "$ git add ."
git add .
echo " "

echo -e "$ git commit -m \"$commit_message\""
git commit -m "$commit_message"
echo " "

if [ $# -eq 3 ]; then
	echo -e "$ git push -u '$2' '$3'"
	git push -u "$2" "$3"
elif [ $# -eq 2 ]; then
	echo -e "ERROR: If there is a commit message and remote specified, then there must be a branch specified as well."
	exit 1
else
	echo -e "$ git push -u origin main"
	git push -u origin main
fi

echo " "

echo -e "$ git status"
git status

echo " "
echo "======================================== AutoGit ========================================"
